const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/domain/engine.js'),A=require('../src/application/game.js'),S=require('../src/infrastructure/save.js');
function state(seed=808){return E.create({mode:'player',world:'legacy',clubId:'c0',name:'Teste',pos:'ATA'},seed)}
function fakeMatch(s,{goals=0,rating=8.2,played=true}={}){const opp=s.clubs.find(c=>c.id!==s.clubId);return {home:s.clubId,away:opp.id,hg:goals,ag:0,date:s.day,season:s.season,competitionId:'test',leagueId:'horizonte',ratings:played?{hero:rating}:{},playerStats:played?{hero:{minutes:90,starter:true}}:{},events:Array.from({length:goals},(_,i)=>({type:'goal',playerId:'hero',minute:10+i*10}))};}
test('hat-trick gera evento/noticia contextual uma unica vez',()=>{const s=state(),m=fakeMatch(s,{goals:3});E.Career.match(s,m);E.Career.processMatchEvent(s,m);E.Career.processMatchEvent(s,m);const c=E.Career.init(s).communications;assert.equal(c.events.filter(e=>e.type==='PLAYER_HAT_TRICK').length,1);assert.equal(c.articles.filter(n=>/hat-trick/i.test(n.title)).length,1)});
test('mensagem lida persiste em save/load',()=>{const s=state();E.Career.addMessage(s,{category:'AGENTE',sender:'Agente',subject:'Teste',body:'Mensagem'});const id=E.Career.init(s).communications.messages[0].id;A.execute(s,'markMessageRead',{id});const loaded=S.parse(JSON.stringify(s));assert.equal(E.Career.init(loaded).communications.messages.find(m=>m.id===id).read,true)});
test('post do agente alimenta inbox sem duplicar mesmo evento',()=>{const s=state();E.Career.post(s,'Carreira','Agente','Contato','Um clube observa você.');const c=E.Career.init(s).communications;assert.equal(c.messages.filter(m=>m.subject==='Contato').length,1);assert.equal(c.events.filter(e=>e.type==='COMMUNICATION'&&e.data.title==='Contato').length,1)});
test('transferencia confirmada gera comunicacao coerente',()=>{const s=state(),from=E.club(s),to=s.clubs.find(c=>c.id!==s.clubId);E.Career.transfer(s,s.person,from,to,1000000);const c=E.Career.init(s).communications;assert.ok(c.events.some(e=>e.type==='COMMUNICATION'));assert.ok(c.messages.some(m=>/Transferência confirmada/.test(m.subject)))});
test('mesma seed e mesmas acoes mantem comunicacoes deterministicas',()=>{const a=state(812),b=state(812);for(let i=0;i<90;i++){E.advance(a,1);E.advance(b,1)}assert.deepEqual(E.Career.init(a).communications,E.Career.init(b).communications)});
test('save antigo recebe estrutura nova sem inventar historico',()=>{const s=state();delete s.extras.communications;const loaded=S.parse(JSON.stringify(s));const c=E.Career.init(loaded).communications;assert.deepEqual(c.events,[]);assert.deepEqual(c.messages,[]);assert.deepEqual(c.articles,[])});
test('entrevista contextual tem resposta e consequencia moderada',()=>{const s=state(),m=fakeMatch(s,{goals:3,rating:9});E.Career.match(s,m);E.Career.processMatchEvent(s,m);const c=E.Career.init(s).communications,i=c.interviews.find(x=>!x.answered);assert.ok(i);const before={rep:s.reputation,morale:s.person.morale};A.execute(s,'respondInterview',{id:i.id,choice:'team'});assert.equal(i.answered,true);assert.ok(s.reputation-before.rep<=2);assert.ok(s.person.morale-before.morale<=2);assert.equal(c.responses.length,1)});

test("decisao respondida permanece registrada na caixa de entrada", () => {
  const s = state(808);
  s.decision = { id:"family", title:"Um fim de semana em família", body:"Teste", choices:[["visit","Visitar a família"],["work","Priorizar o trabalho"]] };
  E.decide(s,"visit");
  const messages = E.Career.init(s).communications.messages;
  assert.equal(s.decision, null);
  assert.ok(messages.some((m)=>m.subject==="Escolha registrada" && m.body.includes("Visitar a família")));
});

test("caixa expira mensagens antigas sem apagar acao ainda valida",()=>{const s=state(900);const c=E.Career.init(s).communications;E.Career.addMessage(s,{category:"TREINADOR",sender:"Treinador",subject:"Comum",body:"Antiga"});E.Career.addMessage(s,{category:"AGENTE",sender:"Agente",subject:"Pendente",body:"Responder",priority:"URGENT",action:"offer",deadline:s.day+100});const common=c.messages.find(m=>m.subject==="Comum"),pending=c.messages.find(m=>m.subject==="Pendente");s.day+=61;E.Career.pruneMessages(s);assert.equal(c.messages.some(m=>m.id===common.id),false);assert.equal(c.messages.some(m=>m.id===pending.id),true);s.day=pending.deadline+121;E.Career.pruneMessages(s);assert.equal(c.messages.some(m=>m.id===pending.id),false);});
test("limpeza da caixa persiste em save e nao recria mensagem expirada",()=>{const s=state(901);E.Career.addMessage(s,{category:"CARREIRA",sender:"PRO LIFE",subject:"Temporaria",body:"Teste"});s.day+=61;E.Career.pruneMessages(s);const loaded=S.parse(JSON.stringify(s));assert.equal(E.Career.init(loaded).communications.messages.some(m=>m.subject==="Temporaria"),false);});
