const test=require("node:test"),assert=require("node:assert/strict");
const E=require("../src/domain/engine.js"),A=require("../src/application/game.js"),Save=require("../src/infrastructure/save.js");
function career(seed=1200){const s=E.create({mode:"player",world:"legacy",name:"Alesson",age:22,pos:"ATA",points:{}},seed);E.movePlayerToClub(s,s.clubs[0].id);const pc=E.Career.init(s).playerCareer;s.salary=20000;s.contract=1500;pc.contract={clubId:s.clubId,signedDay:0,endDay:1500,durationDays:1500,salary:20000,signingBonus:0,role:"Titular",type:"permanent"};return s;}
function elevate(s,pop=75,rep=80){s.reputation=rep;const c=E.Commercial.init(s,E);c.popularity=pop;c.followers=Math.round(1000*Math.pow(1.09,pop));c.lastFansSnapshot=s.fans;E.Commercial.updateValue(s,E);return c;}
function proposal(s,brandId="vertex"){const c=elevate(s),b=E.Commercial.brands.find(x=>x.id===brandId);c.interests.push({brandId:b.id,stage:"NEGOCIAÇÃO",score:90,startedDay:s.day,updatedDay:s.day,ticks:4});for(let i=0;i<2;i++){s.day+=14;E.Commercial.progressInterests(s,new E.Random(s.rng),E.Career,E);}return c.proposals.find(p=>p.brandId===brandId);}
test("Etapa 12: reputação, popularidade, valor esportivo e comercial permanecem separados",()=>{const s=career();const c=E.Commercial.init(s,E),market=E.Career.init(s).playerCareer.marketValue;c.popularity=85;const high=E.Commercial.updateValue(s,E);c.popularity=25;const low=E.Commercial.updateValue(s,E);assert(high>low);assert.equal(s.reputation,15);assert.equal(E.Career.init(s).playerCareer.marketValue,market);});
test("Etapa 12: marcas possuem categorias e critérios próprios",()=>{assert(E.Commercial.brands.length>=8);assert(new Set(E.Commercial.brands.map(x=>x.category)).size>=7);assert(E.Commercial.brands.every(x=>x.minPopularity>=0&&x.minReputation>=0&&x.budget>0&&x.age.length===2));});
test("Etapa 12: perfis A-D destravam marcas em patamares coerentes",()=>{const a=career(3),b=career(4),c=career(5),d=career(6);elevate(a,10,12);elevate(b,38,38);elevate(c,72,76);elevate(d,92,92);c.nationalTeam.caps=5;d.nationalTeam.caps=25;const eligible=s=>E.Commercial.brands.filter(x=>E.Commercial.eligible(s,x,E)).map(x=>x.id);assert.equal(eligible(a).length,0);assert(eligible(b).includes("vertex"));assert(eligible(c).includes("nova"));assert(eligible(d).includes("aureo"));});
test("Etapa 12: perfis comerciais evoluem sem depender somente do overall",()=>{const low=career(1),popular=career(2);low.reputation=75;elevate(low,25,75);popular.reputation=65;elevate(popular,85,65);for(const k of Object.keys(low.person.attrs))low.person.attrs[k]=90;for(const k of Object.keys(popular.person.attrs))popular.person.attrs[k]=82;assert(E.overall(low.person)>E.overall(popular.person));assert(E.Commercial.updateValue(popular,E)>E.Commercial.updateValue(low,E));assert(E.Commercial.scoreBrand(popular,E.Commercial.brands[2],E)>E.Commercial.scoreBrand(low,E.Commercial.brands[2],E));});
test("Etapa 12: interesse segue pipeline determinístico até proposta real",()=>{const a=career(10),b=JSON.parse(JSON.stringify(a));elevate(a,80,85);elevate(b,80,85);for(let i=0;i<6;i++){a.day+=14;b.day+=14;E.Commercial.progressInterests(a,new E.Random(99+i),E.Career,E);E.Commercial.progressInterests(b,new E.Random(99+i),E.Career,E);}assert(a.commercial.proposals.length>0);assert.deepEqual(a.commercial.interests,b.commercial.interests);assert.deepEqual(a.commercial.proposals,b.commercial.proposals);});
test("Etapa 12: proposta permite pedir tempo, negociar, recusar e aceitar",()=>{const s=career(20),p=proposal(s);assert(p);const old=p.expires;A.execute(s,"commercialHold",{id:p.id});assert(p.expires>old);const result=A.execute(s,"commercialNegotiate",{id:p.id,amount:p.amount,durationDays:p.durationDays,bonus:p.bonus.amount});assert(["ACEITA","CONTRAPROPOSTA"].includes(result));A.execute(s,"commercialAccept",{id:p.id});assert.equal(E.Commercial.active(s).length,1);const other=career(21),p2=proposal(other);A.execute(other,"commercialReject",{id:p2.id});assert.equal(p2.status,"RECUSADA");});
test("Etapa 12: exclusividade bloqueia dois contratos incompatíveis",()=>{const s=career(30),a=proposal(s,"vertex");A.execute(s,"commercialAccept",{id:a.id});const c=E.Commercial.init(s,E),nova=E.Commercial.brands.find(x=>x.id==="nova");c.proposals.unshift({ ...a,id:"manual-nova",brandId:nova.id,brand:nova.name,status:"PROPOSTA",startDay:s.day+1,endDay:s.day+365,expires:s.day+10,round:0 });assert.throws(()=>A.execute(s,"commercialAccept",{id:"manual-nova"}),/Exclusividade/);});
test("Etapa 12: pagamento usa wallet e ledger uma única vez após reload",()=>{const s=career(40),p=proposal(s);A.execute(s,"commercialAccept",{id:p.id});const contract=E.Commercial.active(s)[0],before=s.wallet;s.day=contract.startDay;E.Commercial.processContracts(s,E.Career,E);assert.equal(s.wallet,before+contract.amount);assert.equal(E.Career.init(s).ledger.filter(x=>x.label===`Patrocínio — ${contract.brand}`).length,1);const loaded=Save.parse(JSON.stringify(s));E.Commercial.processContracts(loaded,E.Career,E);assert.equal(loaded.wallet,s.wallet);assert.equal(E.Career.init(loaded).ledger.filter(x=>x.label===`Patrocínio — ${contract.brand}`).length,1);});
test("Etapa 12: 30 dias em massa equivalem a 30 avanços diários",()=>{const a=career(50),p=proposal(a);A.execute(a,"commercialAccept",{id:p.id});const b=Save.parse(JSON.stringify(a));E.advance(a,30);for(let i=0;i<30;i++)E.advance(b,1);assert.equal(a.wallet,b.wallet);assert.deepEqual(a.commercial,b.commercial);assert.deepEqual(E.Career.init(a).ledger,E.Career.init(b).ledger);});
test("Etapa 12: evento comercial não ocupa o dia de partida",()=>{const s=career(60),p=proposal(s);A.execute(s,"commercialAccept",{id:p.id});const x=E.Commercial.active(s)[0],event=s.commercial.events[0];event.day=s.calendarDays[0];event.status="AGENDADO";s.day=event.day;E.Commercial.processContracts(s,E.Career,E);assert.equal(event.status,"REAGENDADO");assert.equal(event.day,s.day+1);assert.equal(x.relationship,70);});
test("Etapa 12: evento concluído afeta exposição sem comprar atributos",()=>{const s=career(70),p=proposal(s);A.execute(s,"commercialAccept",{id:p.id});const event=s.commercial.events[0],attrs=JSON.stringify(s.person.attrs),followers=s.commercial.followers;event.day=++s.day;E.Commercial.processContracts(s,E.Career,E);assert.equal(event.status,"CONCLUÍDO");assert(s.commercial.followers>followers);assert.equal(JSON.stringify(s.person.attrs),attrs);});
test("Etapa 12: save antigo inicia estado seguro sem inventar contratos",()=>{const s=career(80);delete s.commercial;const loaded=Save.parse(JSON.stringify(s));const c=E.Commercial.init(loaded,E);assert.equal(c.contracts.length,0);assert.equal(c.proposals.length,0);assert(c.followers>=100);});
test("Etapa 12: contratos expiram e renovação depende de relação",()=>{const s=career(90),p=proposal(s);A.execute(s,"commercialAccept",{id:p.id});const x=E.Commercial.active(s)[0];x.endDay=s.day+30;E.Commercial.processContracts(s,E.Career,E);assert(s.commercial.proposals.some(p=>p.renewalOf===x.id));s.day=x.endDay+1;E.Commercial.processContracts(s,E.Career,E);assert.equal(x.status,"ENCERRADO");});
test("Etapa 12: campanha pontual e decisões de evento funcionam",()=>{const s=career(95),p=proposal(s,"linha");assert.equal(p.type,"CAMPANHA PONTUAL");A.execute(s,"commercialAccept",{id:p.id});let e=s.commercial.events[0];const original=e.day;A.execute(s,"commercialEvent",{id:e.id,choice:"reschedule"});assert(e.day>original);A.execute(s,"commercialEvent",{id:e.id,choice:"participate"});assert.equal(e.status,"CONFIRMADO");s.day=e.day;E.Commercial.processContracts(s,E.Career,E);assert.equal(e.status,"CONCLUÍDO");});
test("Etapa 12: recusas importantes repetidas podem encerrar contrato",()=>{const s=career(96),p=proposal(s);A.execute(s,"commercialAccept",{id:p.id});const x=E.Commercial.active(s)[0],c=s.commercial;x.relationship=45;for(let i=0;i<3;i++){const e={id:`manual-event-${i}`,contractId:x.id,brandId:x.brandId,brand:x.brand,day:s.day+i+1,type:"CAMPANHA",status:"AGENDADO",mandatory:true,reschedules:0};c.events.push(e);A.execute(s,"commercialEvent",{id:e.id,choice:"decline"});}assert.equal(x.status,"ENCERRADO");assert.equal(x.warnings,3);});
test("Etapa 12: atuação real aumenta público sem alterar overall",()=>{const s=career(100),c=E.Commercial.init(s,E),before=c.followers,ovr=E.overall(s.person);E.Commercial.onMatch(s,{ratings:{hero:8.7},events:[{type:"goal",playerId:"hero"},{type:"goal",playerId:"hero"}]},E.Career,E);assert(c.followers>before);assert.equal(E.overall(s.person),ovr);});
test("Etapa 12: arquivo longo compacta NPCs sem perder o histórico do jogador",()=>{const s=career(110);for(let year=2026;year<=2028;year++){s.season=year;const stats=E.Statistics.init(s).root,league=E.club(s).leagueId;stats.players.hero.appearances=year-2000;stats.players.hero.byCompetition[league]={appearances:10,starts:10,minutes:900,goals:4,assists:2,motm:1,ratingTotal:72,saves:0,tackles:5,shots:20,onTarget:10,xg:4,yellowCards:0,redCards:0};const npc=s.clubs[0].roster.find(x=>x.id!=="hero");stats.players[npc.id]={appearances:10,starts:10,minutes:900,goals:2,assists:1,motm:0,ratingTotal:68,saves:0,tackles:4,shots:10,onTarget:4,xg:2,yellowCards:0,redCards:0,byCompetition:{[league]:{appearances:10,starts:10,minutes:900,goals:2,assists:1,motm:0,ratingTotal:68,saves:0,tackles:4,shots:10,onTarget:4,xg:2,yellowCards:0,redCards:0}},byClub:{}};E.Statistics.closeSeason(s);}assert.equal(Object.keys(s.statistics.players).length,1);assert(s.statistics.players.hero);assert.equal(s.statistics.seasons[2].compact,true);assert.equal(s.statistics.seasons[2].teams.length,0);assert(s.statistics.seasons[2].panorama.every(x=>Array.isArray(x.team)&&x.team.length===0));assert(s.statistics.seasons[2].player);assert.equal(s.statistics.seasons[0].compact,undefined);});
test("Etapa 12: retenção comercial preserva pendências e limita históricos encerrados",()=>{const s=career(120),c=E.Commercial.init(s,E);c.proposals=Array.from({length:140},(_,i)=>({id:`p${i}`,status:i<3?"PROPOSTA":"EXPIRADA"}));c.events=Array.from({length:140},(_,i)=>({id:`e${i}`,status:i<2?"AGENDADO":"CONCLUÍDO"}));c.history=Array.from({length:140},(_,i)=>({id:i}));E.Commercial.init(s,E);assert.equal(c.proposals.filter(x=>x.status==="PROPOSTA").length,3);assert(c.proposals.length<=100);assert.equal(c.events.filter(x=>x.status==="AGENDADO").length,2);assert(c.events.length<=100);assert.equal(c.history.length,80);});
