const test=require('node:test');const assert=require('node:assert/strict');
const E=require('../src/domain/engine.js');const A=require('../src/application/game.js');
function career(seed=111){const s=E.create({mode:'player',world:'legacy',name:'Alesson',age:20,pos:'ATA',points:{}},seed);E.movePlayerToClub(s,s.clubs[0].id);const pc=E.Career.init(s).playerCareer;s.salary=10000;s.contract=365;pc.contract={clubId:s.clubId,signedDay:0,endDay:365,durationDays:365,salary:10000,signingBonus:0,role:'Titular',type:'permanent'};pc.agent={id:'x',name:'Agente',agency:'Teste',commission:5};return s}
test('Etapa 11: salário vem do contrato, comissão e ledger processam uma vez',()=>{const s=career();const before=s.wallet;E.advance(s,30);assert.equal(s.wallet,before+10000-500-650);const labels=E.Career.init(s).ledger.map(x=>x.label);assert(labels.includes('Salário mensal'));assert(labels.includes('Comissão da agência'));const after=s.wallet;E.Life.monthlyFinance(s,E.Career);assert.equal(s.wallet,after)});
test('Etapa 11: 30 dias em massa equivale a 30 x 1 dia financeiramente',()=>{const a=career(222),b=JSON.parse(JSON.stringify(a));E.advance(a,30);for(let i=0;i<30;i++)E.advance(b,1);assert.equal(a.wallet,b.wallet);assert.deepEqual(E.Career.init(a).ledger,E.Career.init(b).ledger);assert.deepEqual(E.Life.snapshot(a),E.Life.snapshot(b))});
test('Etapa 11: moradia, veículo, venda e patrimônio usam saldo real',()=>{const s=career();s.wallet=1000000;A.execute(s,'lifeHousing',{id:'buy-modern'});A.execute(s,'lifeVehicle',{id:'popular'});const f=E.Life.snapshot(s);assert.equal(f.housing.value,420000);assert.equal(f.vehicles.length,1);assert(f.netWorth>s.wallet);const old=s.wallet;A.execute(s,'lifeSellVehicle',{id:'popular'});assert(s.wallet>old);assert.equal(E.Life.snapshot(s).vehicles.length,0)});
test('Etapa 11: visitar família tem custo, efeito e cooldown',()=>{const s=career();const w=s.wallet,fam=s.family;A.execute(s,'lifeActivity',{id:'family'});assert.equal(s.wallet,w-150);assert(s.family>fam);assert.throws(()=>A.execute(s,'lifeActivity',{id:'family'}),/cooldown/)});
test('Etapa 11: investimento respeita saldo e persiste',()=>{const s=career();s.wallet=100000;A.execute(s,'lifeInvest',{id:'conservative',amount:10000});assert.equal(E.Life.snapshot(s).investments.length,1);assert.equal(s.wallet,90000);const copy=JSON.parse(JSON.stringify(s));E.Life.init(copy);assert.equal(E.Life.snapshot(copy).investments[0].principal,10000)});
test('Etapa 11: migração antiga inicia economia sem salários retroativos',()=>{const s=career();delete s.life;const wallet=s.wallet;const life=E.Life.init(s);assert.equal(s.wallet,wallet);assert.equal(life.finance.startedDay,s.day);assert.equal(E.Career.init(s).ledger.length,0)});
test('Etapa 11 V2: catálogo possui investimentos diversificados e perdas são raras',()=>{const types=E.Life.investmentTypes;assert(types.length>=10);assert(new Set(types.map(x=>x.category)).size>=6);assert(types.filter(x=>x.lossChance===0).length>=2);assert(types.every(x=>Number(x.lossChance||0)<=.11))});
test('Etapa 11 V2: compras pessoais geram benefício moderado sem comprar atributos',()=>{const s=career();s.wallet=100000;const attrs=JSON.stringify(s.person.attrs);const before=s.person.condition;A.execute(s,'lifePurchase',{id:'recovery'});const f=E.Life.snapshot(s);assert(f.possessions.some(x=>x.id==='recovery'));assert(s.person.condition>=before);assert.equal(JSON.stringify(s.person.attrs),attrs);assert.throws(()=>A.execute(s,'lifePurchase',{id:'recovery'}),/já adquirido/)});
test('Etapa 11 V2: luxo respeita progressão financeira',()=>{const s=career();s.wallet=4000000;assert.throws(()=>A.execute(s,'lifeVehicle',{id:'super'}),/não disponível/);s.extras.playerCareer.contract.salary=300000;A.execute(s,'lifeVehicle',{id:'super'});assert(E.Life.snapshot(s).vehicles.some(x=>x.id==='super'))});
test('Etapa 11 V2: resultado de investimento é determinístico após save reload',()=>{const s=career(333);s.wallet=200000;A.execute(s,'lifeInvest',{id:'fund',amount:20000});const copy=JSON.parse(JSON.stringify(s));E.advance(s,300);E.advance(copy,300);assert.equal(s.wallet,copy.wallet);assert.deepEqual(E.Career.init(s).ledger,E.Career.init(copy).ledger)});
test('Etapa 11 V2 FIX: investimento liquida exatamente no vencimento diário e não duplica',()=>{const s=career(444);s.wallet=100000;A.execute(s,'lifeInvest',{id:'conservative',amount:5000});const inv=E.Life.snapshot(s).investments[0],days=inv.maturesDay-s.day;for(let i=0;i<days-1;i++)E.advance(s,1);assert.equal(E.Life.snapshot(s).investments.length,1);const before=s.wallet;E.advance(s,1);assert.equal(E.Life.snapshot(s).investments.length,0);assert(s.wallet>before);const returns=E.Career.init(s).ledger.filter(x=>x.label==='Retorno: Reserva conservadora');assert.equal(returns.length,1);const paid=s.wallet;E.advance(s,1);assert.equal(E.Career.init(s).ledger.filter(x=>x.label==='Retorno: Reserva conservadora').length,1);assert.notEqual(paid,undefined)});
