"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const D=require("../src/domain/engine.js"),A=require("../src/application/game.js"),Save=require("../src/infrastructure/save.js");
function state(seed=61){const s=D.create({mode:"player",clubId:"c0"},seed);D.Career.init(s);D.Squad.init(s);return s;}
function rival(s){return D.club(s).roster.filter(p=>p.id!=="hero"&&p.pos===s.person.pos).sort((a,b)=>D.overall(b)-D.overall(a))[0];}
test("cenario A: OVR inferior com baixa confianca comeca fora do XI e pode evoluir por merito",()=>{const s=state();const r=rival(s);Object.values(s.person.attrs).forEach(k=>{});for(const k of Object.keys(s.person.attrs))s.person.attrs[k]=55;for(const k of Object.keys(r.attrs))r.attrs[k]=82;D.Career.init(s).playerCareer.coachTrust=35;s.person.condition=100;s.person.morale=55;let q=D.Squad.competition(s);assert.notEqual(q.heroRole,"Titular");D.Career.init(s).playerCareer.coachTrust=92;for(const k of Object.keys(s.person.attrs))s.person.attrs[k]=88;s.person.morale=90;q=D.Squad.competition(s);assert.equal(q.heroRole,"Titular");});
test("cenario B/C: forma e fadiga podem tirar titular sem tornar decisao aleatoria",()=>{const s=state(62),pc=D.Career.init(s).playerCareer;for(const k of Object.keys(s.person.attrs))s.person.attrs[k]=90;pc.coachTrust=90;s.person.condition=100;s.person.morale=90;assert.equal(D.Squad.competition(s).heroRole,"Titular");s.person.condition=20;assert.equal(D.Squad.competition(s).heroRole,"Fora da relação");});
test("cenario D: reserva pode entrar e minutos refletem somente periodo em campo",()=>{const s=state(63),c=D.club(s),pc=D.Career.init(s).playerCareer,r=rival(s);for(const k of Object.keys(r.attrs))r.attrs[k]=95;pc.coachTrust=75;s.person.condition=100;s.person.morale=90;const sel=D.Squad.choose(s,c);c.lineup=sel.starters.map(p=>p.id);pc.matchSelection={day:s.day,role:"Banco",bench:["hero"]};let found=null;for(let seed=1;seed<80&&!found;seed++){const copy=structuredClone(s),m=D.simulate(D.club(copy),D.club(copy,copy.fixtures[0].find(x=>x.includes(copy.clubId)).find(x=>x!==copy.clubId)),new D.Random(seed),copy);if(m.playerStats?.hero?.starter===false)found=m;}assert.ok(found);assert.ok(found.playerStats.hero.minutes>0&&found.playerStats.hero.minutes<90);assert.ok(found.playerStats.hero.entryMinute>=58&&found.playerStats.hero.entryMinute<=82);});
test("cenario E: reserva nao utilizado nao recebe atuacao",()=>{const s=state(64),c=D.club(s),pc=D.Career.init(s).playerCareer,r=rival(s);for(const k of Object.keys(r.attrs))r.attrs[k]=96;pc.coachTrust=10;s.person.morale=20;s.person.condition=100;const sel=D.Squad.choose(s,c);c.lineup=sel.starters.map(p=>p.id);pc.matchSelection={day:s.day,role:"Banco",bench:["hero"]};const oppId=s.fixtures[0].find(x=>x.includes(s.clubId)).find(x=>x!==s.clubId),m=D.simulate(c,D.club(s,oppId),new D.Random(2),s);if(!m.ratings.hero){assert.equal(m.playerStats?.hero,undefined);assert.ok(!m.participation?.hero);}});
test("treino manual influencia confianca gradualmente",()=>{const s=state(65),pc=D.Career.init(s).playerCareer,before=pc.coachTrust;const ex=Object.values(D.Training.exercises).find(x=>D.Training.trainingCategories[x.category].positions.includes(s.person.pos));A.execute(s,"train",{exerciseId:ex.id,focus:"balanced",intensity:"normal",style:s.person.style});assert.ok(Math.abs(pc.coachTrust-before)<=1.21);});

test("Etapa 6 persiste disputa e decisao do treinador em reload",()=>{const s=state(66),q=D.Squad.competition(s);D.Squad.recordDecision(s,q.heroRole,"Teste persistente");const restored=Save.parse(JSON.stringify(s));assert.equal(D.Squad.init(restored).lastDecision.role,q.heroRole);assert.equal(D.Squad.competition(restored).heroRole,q.heroRole);});

test("oportunidade de reserva melhora com confianca, treino, forma e condicao",()=>{const s=state(67),pc=D.Career.init(s).playerCareer,q=D.Squad.init(s);s.person.condition=100;s.person.morale=85;pc.coachTrust=35;q.trainingTrend=-1;const low=D.Squad.substitutePlan(s,s.person);pc.coachTrust=78;q.trainingTrend=3;const high=D.Squad.substitutePlan(s,s.person);assert.ok(high.chance>low.chance);assert.ok(high.minute<low.minute);});
test("treino automatico aumenta avaliacao do tecnico de forma menor que treino manual",()=>{const s=state(68),pc=D.Career.init(s).playerCareer,q=D.Squad.init(s),before=pc.coachTrust;D.Squad.trainingResult(s,{available:true,automatic:true,grade:"A"});const auto=pc.coachTrust-before;pc.coachTrust=before;q.trainingTrend=0;D.Squad.trainingResult(s,{available:true,automatic:false,grade:"A"});const manual=pc.coachTrust-before;assert.ok(auto>0);assert.ok(manual>auto);});
test("transferencia para novo clube recalibra hierarquia e escalação usa o mesmo motor",()=>{const s=state(69),pc=D.Career.init(s).playerCareer;pc.coachTrust=95;D.Career.updatePlayerRole(s);assert.equal(pc.squadRole,"Estrela");s.careerTransferAvailableDay=0;s.offers=[{clubId:"c1",salary:12000,durationDays:730,signingBonus:0,squadRole:"Estrela",transferType:"permanent",expires:s.day+10}];D.join(s,"c1",12000);assert.ok(pc.coachTrust<=60);assert.notEqual(pc.squadRole,"Estrela");const a=D.Squad.competition(s),b=D.Squad.roleForHero(s,D.Squad.choose(s,D.club(s)));assert.equal(a.heroRole,b);});
