(function(root){
  "use strict";
  let session=null,timer=null;
  const esc=(v)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  function scoreAt(m,min){let h=0,a=0;(m.events||[]).forEach(e=>{if(e.type==="goal"&&e.minute<=min)e.side===0?h++:a++;});return [h,a];}
  function dot(i,side,min){const row=Math.floor(i/3),col=i%3;const baseX=side?58:12;const x=baseX+col*8+Math.sin((min+i*7)*.17)*3;const y=10+row*21+Math.cos((min+i*5)*.13)*5;return `<i class="lm-player lm-${side?'away':'home'}" style="left:${x}%;top:${y}%">${i+1}</i>`;}
  function paint(){if(!session)return;const {match:m,home,away}=session,min=session.minute,[hg,ag]=scoreAt(m,min),heroPart=m.participation?.hero,hero=heroPart?min>=Number(heroPart.entryMinute||0)&&min<=Number(heroPart.exitMinute??94):m.participants?.flat().includes("hero"),heroRating=m.ratings?.hero;const visible=(m.events||[]).filter(e=>e.minute<=min).slice().sort((a,b)=>b.minute-a.minute).slice(0,9);const el=document.getElementById("live-match-overlay");if(!el)return;
    el.innerHTML=`<div class="lm-shell"><header class="lm-header"><div><small>${esc(m.competitionName||"PARTIDA")}</small><b>${esc(home.name)} <strong>${hg} - ${ag}</strong> ${esc(away.name)}</b></div><div class="lm-clock">${min<46?"1º TEMPO":min<91?"2º TEMPO":"ACRÉSCIMOS"}<strong>${Math.min(min,94)}'</strong></div><button data-live-close ${min<94?'disabled':''}>${min<94?'EM JOGO':'CONTINUAR'}</button></header><main class="lm-layout"><section class="lm-pitch"><div class="lm-half"></div><div class="lm-circle"></div>${Array.from({length:11},(_,i)=>dot(i,0,min)).join("")}${Array.from({length:11},(_,i)=>dot(i,1,min)).join("")}<span class="lm-ball" style="left:${48+Math.sin(min*.41)*30}%;top:${48+Math.cos(min*.29)*31}%"></span></section><aside class="lm-panel"><div class="lm-score"><span>${esc(home.name)}</span><strong>${hg} - ${ag}</strong><span>${esc(away.name)}</span></div>${hero?`<div class="lm-hero"><small>SEU JOGADOR</small><b>Nota ${heroRating||"—"}</b><span>${(m.offensiveStats?.hero?.goals||0)} gol(s) · ${(m.offensiveStats?.hero?.shots||0)} finalizações · ${m.playerStats?.hero?.minutes||0} min</span></div>`:""}<h3>ACONTECIMENTOS</h3><div class="lm-feed">${visible.length?visible.map(e=>`<article class="${e.type}"><b>${e.minute}'</b><span>${esc(e.text)}</span></article>`).join(""):'<p>A partida começou. As equipes estudam os espaços.</p>'}</div></aside></main><footer class="lm-controls"><button data-live-speed="1" class="${session.speed===1?'active':''}">1x</button><button data-live-speed="2" class="${session.speed===2?'active':''}">2x</button><button data-live-speed="4" class="${session.speed===4?'active':''}">4x</button><button data-live-finish>Simular restante</button><span>Finalizações ${m.shots?.[0]||0} - ${m.shots?.[1]||0} · xG ${m.xg?.[0]||0} - ${m.xg?.[1]||0}</span></footer></div>`;
  }
  function tick(){if(!session||session.minute>=94){clearInterval(timer);timer=null;if(session)session.minute=94;paint();return;}session.minute=Math.min(94,session.minute+session.speed);paint();}
  function restart(){clearInterval(timer);timer=setInterval(tick,700);}
  function start(opts){close();session={...opts,minute:0,speed:1};const el=document.createElement("div");el.id="live-match-overlay";el.className="live-match-overlay";document.body.appendChild(el);paint();restart();}
  function close(){clearInterval(timer);timer=null;document.getElementById("live-match-overlay")?.remove();session=null;}
  if (typeof document !== "undefined") document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b||!session)return;if(b.dataset.liveSpeed){session.speed=Number(b.dataset.liveSpeed);paint();return;}if(b.hasAttribute("data-live-finish")){session.minute=94;clearInterval(timer);timer=null;paint();return;}if(b.hasAttribute("data-live-close")&&session.minute>=94)close();});
  const API={start,close,scoreAt};if(typeof module!=="undefined"&&module.exports)module.exports=API;root.ProLifeLiveMatch=API;
})(typeof globalThis!=="undefined"?globalThis:this);
