"use strict";
const files = [
  "index.html",
  "src/domain/character.js",
  "src/domain/world2026.js",
  "src/domain/brazil-data.js",
  "src/domain/competitions.js",
  "src/domain/training.js",
  "src/domain/statistics.js",
  "src/domain/life.js",
  "src/domain/career.js",
  "src/domain/national-team.js",
  "src/ui/avatar3d.js",
  "src/ui/charts.js",
  "src/domain/engine.js",
  "src/application/game.js",
  "src/infrastructure/save.js",
  "src/infrastructure/codec.js",
  "src/infrastructure/validate-expansion.js",
  "src/ui/expansion.js",
  "src/ui/calendar.js",
  "src/ui/app.js",
  "src/ui/style.css",
  "src/ui/update.js",
];
module.exports = { files };
